---
- name: List default Grafana dashboards folders
  command: az grafana folder list --name {{managedGrafanaName}} --resource-group {{resourceGroup}} --query '[].uid' --output tsv
  register: default_dashboards
  delegate_to: localhost

- name: Delete default Grafana dashboards folders
  command: az grafana folder delete --name {{managedGrafanaName}} --resource-group {{resourceGroup}} --folder {{item}}
  loop: "{{default_dashboards.stdout_lines}}"
  delegate_to: localhost

- name: Create Slurm Cluster dashboards folder
  command: az grafana folder create --name {{managedGrafanaName}} --resource-group {{resourceGroup}} --title 'Slurm Cluster'
  delegate_to: localhost

- name: List Grafana dashboard template files
  find:
    paths: "{{role_path}}/files/dashboards/"
    file_type: file
  delegate_to: localhost
  register: dashboard_templates

- name: Import Grafana dashboard templates
  command: az grafana dashboard import --name {{managedGrafanaName}} --resource-group {{resourceGroup}} --folder 'Slurm Cluster' --definition {{item.path}}
  loop: "{{dashboard_templates.files}}"
  delegate_to: localhost
