---
- name: Get CycleCloud locker name
  shell: cyclecloud locker list | egrep -o '^[^(]+' | xargs
  register: lockerName

- name: Copy cluster template file to CycleCloud server
  template:
    src: "slurm_template.txt.j2"
    dest: "/home/{{cycleserverAdmin}}/slurm_template.txt"

- name: Copy template parameters file to CycleCloud server
  template:
    src: "slurm_params.json.j2"
    dest: "/home/{{cycleserverAdmin}}/slurm_params.json"

- name: List local CycleCloud projects directories
  find:
    paths: "{{role_path}}/files/cc_projects/"
    file_type: any
  delegate_to: localhost
  register: projects_dirs

- name: Upload projects to CycleCloud server
  ansible.posix.synchronize:
    src: "{{role_path}}/files/cc_projects/"
    dest: "/home/{{cycleserverAdmin}}/cc_projects/"
    delete: true
    recursive: true
    copy_links: true
    use_ssh_args: true

- name: Upload CycleCloud projects to locker
  command: cyclecloud project upload '{{lockerName.stdout}}'
  args:
    chdir: /home/{{cycleserverAdmin}}/cc_projects/{{item.path | basename}}
  loop: "{{projects_dirs.files}}"

- name: Import Slurm cluster
  command: cyclecloud import_cluster slurmcluster --force -f slurm_template.txt -p slurm_params.json -c Slurm
  args:
    chdir: /home/{{cycleserverAdmin}}

- name: Start Slurm cluster
  command: cyclecloud start_cluster slurmcluster
