---
- name: Prometheus Server setup
  hosts: prometheus
  become: false

  tasks:
  - name: Update OS
    include_role:
      name: "update-{{ ansible_os_family | lower }}"

  - name: Install Docker
    include_role:
      name: docker

  - name: Start Prometheus container
    include_role:
      name: prometheus
    vars:
      prometheus_version: "2.45.3"
      prometheus_port: "9090"
      prometheus_data_dir: "/opt/prometheus"

  - name: Customize Grafana
    include_role:
      name: grafana
