---
- name: Create Prometheus config directory
  file:
    path: "{{ prometheus_data_dir }}/etc"
    state: directory
    mode: 0755
  become: true

- name: Create Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_data_dir }}/etc/prometheus.yml"
  become: true

- name: Run Prometheus Docker container
  docker_container:
    name: prometheus
    image: "prom/prometheus:v{{ prometheus_version }}"
    state: started
    restart: true
    restart_policy: always
    ports:
      - "{{ prometheus_port }}:{{ prometheus_port }}"
    volumes:
      - "{{ prometheus_data_dir }}/etc:/etc/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  become: true

- name: Check if Prometheus container successfully started
  shell: "docker logs prometheus 2>&1 | grep 'Done replaying WAL'"
  register: log_output
  until: "'Done replaying WAL' in log_output.stdout"
  retries: 12
  delay: 5
  changed_when: false
  become: true

- name: Fail if 'Done replaying WAL' not found in log
  fail:
    msg: "Container did not start successfully"
  when: "'Done replaying WAL' not in log_output.stdout"
